from enum import Enum as PyEnum

class TipoVehiculo(PyEnum):
    CAR = 'CAR'
    SUV = 'SUV'
    VAN = 'VAN'
    MINIVAN = 'MINIVAN'
    PICKUP = 'PICKUP'
    TRUCK = 'TRUCK'
    SKID_STEER = 'SKID_STEER'
    MOTORCYCLE ='MOTORCYCLE'

class StatusWorkOrder(PyEnum):
    RECEIVED = 'RECEIVED'
    DIAGNOSIS = 'DIAGNOSIS'
    WAITING_APPROVAL = 'WAITING_APPROVAL'
    APPROVED = 'APPROVED'
    IN_PROGRESS = 'IN_PROGRESS'
    WAITING_PARTS = 'WAITING_PARTS'
    REPAIRED = 'REPAIRED'
    READY_FOR_DELIVERY = 'READY_FOR_DELIVERY'
    COMPLETED = 'COMPLETED'
    CANCELLED = 'CANCELLED'



class WorkOrderItemType(PyEnum):
    DIAGNOSIS = 'DIAGNOSIS'
    LABOR = 'LABOR'
    PART = 'PART'